### ISSUE TITLE
Add CTRL+S keyboard shortcut

### ISSUE THREAD

**Issue by Delivator** [harej/hackerpaste#9]
Would be nice if you could press CTRL+S to save the paste as a new snapshot and maybe CTRL+Shift+S to save to my pastes.

**Comment by harej** [comment]
Deployed.

**Comment by harej** [comment]
Note that CTRL+S saves. CTRL+Shift+S to save to my pastes has not (yet) been implemented.

**Comment by Delivator** [comment]
Yeah thats a cool idea
